trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register')
]

trash_collector/employees/urls.py
from django.urls import path
from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('employee/', views.employee_todays_pickups, name = "home"),
    path('new/',views.create,name='create'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('confirm/<int:customer_id>',views.confirm,name='confirm'),
    path('filter/', views.weekday_filter, name = "filter")

]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=5)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from customers.models import Customer
import datetime
from django.db.models import Q
from django.urls.base import reverse
from .models import Employee


# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    logged_in_user = request.user
    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=logged_in_user)

        context = {
            "employee" : logged_in_employee
        }

        return HttpResponseRedirect(reverse('employees:home'))
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))
    

@login_required
def employee_todays_pickups(request):
    logged_in_employee = request.user
    logged_in_employee = Employee.objects.get(user_id = logged_in_employee)
    # Filters customers down to matching employees zip code
    employee_pickup_list = Customer.objects.filter(zip_code = logged_in_employee.zip_code)
    # Gets the day of the week (Monday, Tuesday, ...)
    day_of_week = datetime.datetime.now()
    day_of_week = day_of_week.strftime("%A")

    #Gets current day in format yyyy-mm-dd
    current_day = datetime.date.today()

    #Filters list to match either day of week or one time pick up on todays date
    employee_pickup_list = employee_pickup_list.filter(Q(weekly_pickup = day_of_week) | Q(one_time_pickup = current_day))

    #Gathers ONLY one-time pickup to refund (already paid)
    OT_pickup_list = employee_pickup_list.filter(one_time_pickup = current_day)

    #Filters list to exclude suspended accounts
    employee_pickup_list = employee_pickup_list.exclude(Q(suspend_start__lt = current_day) & Q(suspend_end__gte = current_day))

    #Filters list to exclude already picked up trash
    employee_pickup_list = employee_pickup_list.exclude(date_of_last_pickup = current_day)

    pickup_list_addresses = []
    for customer in employee_pickup_list:
        pickup_list_addresses.append(customer.address)
        

    context = {
        "pickup_list": employee_pickup_list,
        "employee": logged_in_employee,
        "OT_pickup_list": OT_pickup_list,
        "pickup_list_addresses":pickup_list_addresses
    }

    return render(request, 'employees/index.html', context)

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form,user=logged_in_user,zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip')
        logged_in_employee.name = name_from_form
        logged_in_employee.zip = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee':logged_in_employee
        }
        return render(request,'employees/edit_profile.html',context)

@login_required
def confirm(request,customer_id):
    customer_to_update = Customer.objects.get(pk=customer_id)
    if(customer_to_update.one_time_pickup!=datetime.date.today()):
        customer_to_update.balance += 20.00
    customer_to_update.date_of_last_pickup = datetime.date.today()
    customer_to_update.save()
    return HttpResponseRedirect(reverse('employees:home')) 

@login_required
def weekday_filter(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        day_of_week_filter = request.POST.get('weekday')
        filter_results = Customer.objects.filter(weekly_pickup = day_of_week_filter)
        context = {
            'filter_results':filter_results,
            'day_of_week': day_of_week_filter,
            'logged_in_employee': logged_in_employee
        }
        return render(request,'employees/filter.html',context)
    else:
        context = {
            'logged_in_employee':logged_in_employee
        }
        return render(request,'employees/filter.html', context)
        

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees/employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
    <br />
    <form action="{% url 'employees:edit_profile' %}" method="post">
        {% csrf_token %}
        Name: <input type="name" name="name" id="name">
        <br />
        <br />
        Zip Code: <input type="zip_code" name="zip_code" id="zip_code">
        <br />
        <br />
        <input type="submit" value="Submit">
    </form>
{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    
    <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target= "#navbarSupportedContent"
    aria-controls = "navbarSupportedContent" aria-expanded = "false" aria-label = "Toggle navigation">
    <i class = "fa fa-bars"></i></button>
        <div class="collapse navbar-collapse" id = "navbarSupportedContent">
            <a class="nav-link" href="{% url 'employees:index' %}">Home</a>
            <a class="nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
            <a class="nav-link" href="{% url 'employees:filter' %}">Weekly Filter</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
        </div>
    
{% endblock %}

{% block footer %}

    
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <!-- <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24"> -->
      <small class="d-block mb-3 text-muted">© 2017-2018</small>
    </div>
    <div class="col-6 col-md">
      <h5>Opportunities</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Help</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="../../assets/js/vendor/popper.min.js"></script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        <script src="../../assets/js/vendor/holder.min.js"></script>
        <script>
          Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
          });
        </script>

{% endblock %}

trash_collector/employees/templates/employees/filter.html
{% extends 'employees/employee_base.html' %}

{% block title %}{% block header %} Employee Filter {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello {{ logged_in_employee }}!
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}

  <h1>All Customer Filter</h1>

    <form action="{% url 'employees:filter' %}" method="POST">
      {% csrf_token %}
        <select name="weekday">
            <option value=''>None</option>
            <option value="Monday">Monday</option>
            <option value="Tuesday">Tuesday</option>
            <option value="Wednesday">Wednesday</option>
            <option value="Thursday">Thursday</option>
            <option value="Friday">Friday</option>
            <option value="Wednesday">Saturday</option>
            <option value="Sunday">Sunday</option>
          <input  type="submit" value = "Filter" name = "filter">
        </select>
    </form>

  {% if filter != '' %}
    <div class = "weekly-pickups">
      {% csrf_token %}
        <h2>Customer's whose weekday pickup is {{day_of_week}}</h2>
        {% for customer in filter_results %}
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://maps.googleapis.com/maps/api/staticmap?center={{customer.address}}&zoom=13&size=600x300&maptype=roadmap
        &markers=color:red|{{customer.address}}&key=AIzaSyDDPyEaPsxPfbHYjNlYm0-CkRmccSQqbtA" alt="Customer Location">
        
          <div class="card-body">
          
            <p class="card-title"><b>{{customer.name}}</b></p>
            <p class="card-text">{{customer.address}} {{customer.zip_code}}</p>
            <a href="{% url 'employees:confirm' customer.id %}" class="btn btn-primary">Confirm</a>
          </div>
        </div>
        {% endfor %}
      <br>
    </div>
    {% endif %}
  

{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees/employee_base.html' %}

{% block head %}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
{% endblock %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h3>Hello {{ employee.name }}!</h3><br>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
  
  <style>
    #map {
      height: 400px;
      width: 500px;
    }
  </style>
  
  <div id="map"></div><br>
  
  <script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0SO6OEhZJk8CTA0htz25Ju1BLmtScfoU&callback=initMap">
  </script>


  <script>
    
    async function initMap(){
      var cust_names = [{% for customer in pickup_list %}"{{ customer|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %}];
      var pickup_list = [{% for customer in pickup_list_addresses %}"{{ customer|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %}];
      console.log(pickup_list)

      var latlng = await geocode(pickup_list[0])
      console.log(latlng)
      var options = {
        zoom:14,
        center:{lat:latlng[1],lng:latlng[2]}
      }

      var map = new google.maps.Map(document.getElementById('map'),options);

      for(let i=0;i<pickup_list.length;i++){
        var latlng = await geocode(pickup_list[i])
        console.log(latlng)
        var marker = new google.maps.Marker({
          position:{lat:latlng[1],lng:latlng[2]},
          map: map,
          label: {
            text:cust_names[i],
            color: "orange",
            fontSize: "20px",
            fontWeight: "bold"
          },
          icon: {
              scale: 8.5,
              fillColor: "#F00",
              fillOpacity: 0.4,
              strokeWeight: 0.4,
              
          },
        })
        

      }
      
    }

    
    // var address = document.getElementById("location-input");
   
    async function geocode(address){
      var location = address;
      return axios.get('https://maps.googleapis.com/maps/api/geocode/json',{
        params:{
          address:location,
          key:"KEY GOES HERE"
        }
      })
      .then(async function(response){
        // console.log(response);

        var locationDetails = []
        var formattedAddress = response.data.results[0].formatted_address;
        var lat = response.data.results[0].geometry.location.lat;
        var lng = response.data.results[0].geometry.location.lng;
        
        console.log(response.data.results[0].formatted_address)
        console.log(response.data.results[0].geometry.location.lat)
        console.log(response.data.results[0].geometry.location.lng)
       
        locationDetails.push(formattedAddress)
        locationDetails.push(lat)
        locationDetails.push(lng)
        return Promise.resolve(locationDetails)

      })
      .catch(function(error){
        console.log(error)
      })
    }
  </script>

  
  
  <h3>Today's Pickups</h3>
  <div class = "todays_pickups">
    {% for customer in pickup_list %}
      <div class="card box-shadow"  style="width: 18rem;">
        <!-- <img class="card-img-top" src="https://maps.googleapis.com/maps/api/staticmap?center={{customer.address}}&zoom=13&size=600x300&maptype=roadmap
        &markers=color:red|{{customer.address}}&key=AIzaSyDDPyEaPsxPfbHYjNlYm0-CkRmccSQqbtA" alt="Customer Location">
         -->
        <div class="card-body">
          <p class="card-title"><b>{{customer.name}}</b></p>
          <p class="card-text">Address: {{customer.address}}<br>Zip: {{customer.zip_code}}</p>
          <a href="{% url 'employees:confirm' customer.id %}" class="btn btn-primary">Confirm</a>
        </div>
      </div>
      <br>
    {% endfor %}
  </div>

{% endblock %}