trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register')
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('suspend/', views.suspend_service, name="suspend"),
    path('one_time/', views.one_time_pickup, name="one_time"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('payment/', views.payment , name = "payment"),
    path('about/',views.about,name='about'),
    path('payment/thankyou/', views.submit_payment , name = "thanks")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    weekly_pickup = models.CharField(max_length=9)
    one_time_pickup = models.DateField(null=True, blank=True)
    suspend_start = models.DateField(null=True, blank=True)
    suspend_end = models.DateField(null=True, blank=True)
    date_of_last_pickup = models.DateField(null=True, blank=True)
    balance = models.IntegerField(default=0)

    def __str__(self):
        return self.name

trash_collector/customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from datetime import date

from .models import Customer

@login_required
def index(request):
    # The following line will get the logged-in user (if there is one) within any view function
    logged_in_user = request.user
    try:
        # This line will return the customer record of the logged-in user if one exists
        logged_in_customer = Customer.objects.get(user=logged_in_user)

        today = date.today()
        
        context = {
            'logged_in_customer': logged_in_customer,
            'today': today
        }
        return render(request, 'customers/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('customers:create'))

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        weekly_from_form = request.POST.get('weekly_pickup')
        new_customer = Customer(name=name_from_form, user=logged_in_user, address=address_from_form, zip_code=zip_from_form, weekly_pickup=weekly_from_form)
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/create.html')

@login_required
def suspend_service(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        start_from_form = request.POST.get('start')
        end_from_form = request.POST.get('end')
        logged_in_customer.suspend_start = start_from_form
        logged_in_customer.suspend_end = end_from_form
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/suspend.html', context)

@login_required
def one_time_pickup(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        date_from_form = request.POST.get('date')
        price_from_form = request.POST.get('price')
        logged_in_customer.one_time_pickup = date_from_form
        if(price_from_form=='standard'):
            logged_in_customer.balance += 20
        else:
            logged_in_customer.balance += 29    
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/one_time.html', context)

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        logged_in_customer.name = name_from_form
        logged_in_customer.address = address_from_form
        logged_in_customer.zip_code = zip_from_form
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
        }
        return render(request, 'customers/edit_profile.html', context)

@login_required
def payment(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    context = {
            'logged_in_customer': logged_in_customer
        }
    return render(request, 'customers/payment.html', context)

@login_required
def about(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)
    context = {
        'customer':logged_in_customer
    }
    return render(request,'customers/about.html',context)

def submit_payment(request):
    logged_in_user = request.user
    logged_in_customer = Customer.objects.get(user=logged_in_user)

    logged_in_customer.balance = 0
    logged_in_customer.save()

    return HttpResponseRedirect(reverse('customers:index'))

trash_collector/customers/templates/customers/about.html
{% extends 'customers\customer_base.html' %}

{% block title %} About Us {% endblock %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
{% endblock %}

{% block header %} Hello, {{customer.name}}! We're happy to have you. {% endblock %}

{% block content %}
    
    <style>
        .backgroundColor {
            height: 100%;
            background:#f3f3ec;
            padding: 10px 15px;
            border-radius: 25px;
        }
    </style>

  <main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <!-- <h1 class="display-3">Hello, world!</h1> -->
        <p>We pride ourselves by providing an <i>exceptional</i>, <i>world-class</i> quality of service. Whether it's one bag or thirty, we'll get the job done and we'll do it fast and that's our guarantee.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'customers:one_time' %}" role="button">Schedule a service! »</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col- backgroundColor">
          <h3>Humanitarian Relief</h3>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col- backgroundColor">
            <h3>Donating to Those in Need</h3>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
      </div>
      <br>
      <div class="row">
        <div class="col- backgroundColor">
            <h3>What Makes Us Tick?</h3>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
      </div>

      <hr>

    </div> <!-- /container -->

  </main>

  <footer class="container">
    <p>© Company 2017-2021</p>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
  <script src="../../assets/js/vendor/popper.min.js"></script>
  <script src="../../dist/js/bootstrap.min.js"></script>
{% endblock %}


  

    
  

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %} Customer Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'customers:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    Choose your Weekly Pickup Day: <input type="text" name="weekly_pickup" id="weekly_pickup"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/customers/templates/customers/customer_base.html
{% extends 'base.html' %}

{% block head %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Pricing example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
</head>
{% endblock %}

{% block navbar %}
    <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target= "#navbarSupportedContent"
    aria-controls = "navbarSupportedContent" aria-expanded = "false" aria-label = "Toggle navigation">
    <i class = "fa fa-bars"></i></button>
        <div class="collapse navbar-collapse" id = "navbarSupportedContent">   
            <a class="nav-link" href="{% url 'customers:index' %}">Home</a>               
            <a class="nav-link" href="{% url 'customers:one_time' %}">One-Time Pick Up</a>                
            <a class="nav-link" href="{% url 'customers:suspend' %}">Suspend Service</a>                
            <a class="nav-link" href="{% url 'customers:edit_profile' %}">Edit Profile</a>
            <a class="nav-link" href="{% url 'customers:payment' %}">Make Payment</a>
            <a class="nav-item nav-link" href="{% url 'customers:about' %}">About Us</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
        </div>
{% endblock %}

{% block footer %}

    
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <!-- <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24"> -->
      <small class="d-block mb-3 text-muted">© 2017-2018</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="{% url 'customers:about' %}">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="../../assets/js/vendor/popper.min.js"></script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        <script src="../../assets/js/vendor/holder.min.js"></script>
        <script>
          Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
          });
        </script>

{% endblock %}

trash_collector/customers/templates/customers/edit_profile.html
{% extends 'customers/customer_base.html' %}

{% block title %} Customer Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'customers:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="name" name="name" id="name">
    <br />
    <br />
    Address: <input type="address" name="address" id="address">
    <br />
    <br />
    Zip Code: <input type="zip_code" name="zip_code" id="zip_code">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'customers\customer_base.html' %}

{% block title %} Customer Home {% endblock %}

{% block header %} Customer Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
        Hello {{ logged_in_customer.name }}!<br />
        Address: {{ logged_in_customer.address }} {{logged_in_customer.zip_code }}<br />
        Current balance: $ {{ logged_in_customer.balance }}.00
        {% if logged_in_customer.balance > 0 %}
        <br>
        <a href="{% url 'customers:payment' %}" class = "btn btn-primary">Pay Bill</a>

        {% endif %}
        <br />
        <br />
        Your Weekly Pickup Day: {{ logged_in_customer.weekly_pickup }}
        <br />
        <br />
        {% if logged_in_customer.one_time_pickup %}
          You have an extra pickup scheduled for {{ logged_in_customer.one_time_pickup }}
        {% endif %}
        <br />
        <br />
        {% if today > logged_in_customer.suspend_start and today < logged_in_customer.suspend_end %}
          Your pickups are suspended until {{ logged_in_customer.suspend_end }}
        {% endif %}

  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/one_time.html
{% extends 'customers\customer_base.html' %}

{% block title %} One Time Pickup {% endblock %}

{% block head %}  
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

        <title>Pricing example for Bootstrap</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

        <!-- Bootstrap core CSS -->
        <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="pricing.css" rel="stylesheet">
    </head>
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          <h1 class="display-4">Pricing</h1>
          <p class="lead">At TrashCollector LLC, we have choices! If you need personal pickups or if you are a representative of a business and require more, we have an option for you!</p>
        </div>
    
        <div class="container">
          <div class="card-deck mb-3 text-center">
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Standard</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$20 <small class="text-muted">/ pickup</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>1-10 bags</li>
                  <li>Standard pickup priority</li>
                </ul>
                <form action="{% url 'customers:one_time' %}" method="post">
                  {% csrf_token %}
                  Date of Pick Up:<br> <input type="date" name="date" id="date">
                  <input type = "hidden" name = "price" value = "standard" />
                  <br />
                  <br />
                  <input class="btn btn-lg btn-block btn-primary" type="submit" value="Submit">
                </form>
              </div>
            </div>
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Enterprise</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ pickup</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>10+ bags</li>
                  <li>Priority Pickup</li>
                  <li>Help center access</li>
                </ul>
                <form action="{% url 'customers:one_time' %}" method="post">
                  {% csrf_token %}
                  Date of Pick Up:<br> <input type="date" name="date" id="date">
                  <input type = "hidden" name = "price" value = "enterprise" />
                  <br />
                  <br />
                  <input class="btn btn-lg btn-block btn-primary" type="submit" value="Submit">
                </form>
              </div>
            </div>
          </div>
    
          <!-- <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
              <div class="col-12 col-md">
                <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
                <small class="d-block mb-3 text-muted">© 2017-2018</small>
              </div>
              <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Cool stuff</a></li>
                  <li><a class="text-muted" href="#">Random feature</a></li>
                  <li><a class="text-muted" href="#">Team feature</a></li>
                  <li><a class="text-muted" href="#">Stuff for developers</a></li>
                  <li><a class="text-muted" href="#">Another one</a></li>
                  <li><a class="text-muted" href="#">Last time</a></li>
                </ul>
              </div>
              <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Resource</a></li>
                  <li><a class="text-muted" href="#">Resource name</a></li>
                  <li><a class="text-muted" href="#">Another resource</a></li>
                  <li><a class="text-muted" href="#">Final resource</a></li>
                </ul>
              </div>
              <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="{% url 'customers:about' %}">Team</a></li>
                  <li><a class="text-muted" href="#">Locations</a></li>
                  <li><a class="text-muted" href="#">Privacy</a></li>
                  <li><a class="text-muted" href="#">Terms</a></li>
                </ul>
              </div>
            </div>
          </footer>
         -->
    
    
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="../../assets/js/vendor/popper.min.js"></script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        <script src="../../assets/js/vendor/holder.min.js"></script>
        <script>
          Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
          });
        </script>
       -->
    
   




{% endblock %}

trash_collector/customers/templates/customers/payment.html
{% extends 'customers/customer_base.html' %}

{% block title %} Customer Payment {% endblock %}

{% block header %} Customer Payment Portal {% endblock %}


{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-lg">
                <h3>You have an outstanding balance of ${{logged_in_customer.balance}}</h3>
            </div>
        </div>
    </div>
    <div id="paypal-button-container"></div>

    <script src="https://www.paypal.com/sdk/js?client-id=AQ1zqG2l64iTDaGz1wuh-f3al6A-zjIWcaiwEUBmq0i2Y1BcRmB5BrUluEdo9DVFB-ThHR9xklywQ4So&currency=USD"></script>

<script>

    var total = '{{logged_in_customer.balance}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: total
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(orderData) {
                // Successful capture! For demo purposes:
                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                var transaction = orderData.purchase_units[0].payments.captures[0];
                alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                
                location.href = 'thankyou/'
            });
        }


    }).render('#paypal-button-container');
</script>

{% endblock %}

trash_collector/customers/templates/customers/suspend.html
{% extends 'customers\customer_base.html' %}

{% block title %} Customer Suspension {% endblock %}

{% block header %} Choose Suspension Dates {% endblock %}

{% block content %}
<br />
<form action="{% url 'customers:suspend' %}" method="post">
    {% csrf_token %}
    Start Date: <input type="date" name="start" id="start">
    <br />
    <br />
    End Date: <input type="date" name="end" id="end">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/customers/templates/customers/thank_you.html
{% extends 'customers/customer_base.html' %}

{% block title %} Payment Success {% endblock %}

{% block header %} Thank You! {% endblock %}


{% block content %}
    <p>Payment Successful</p>
{% endblock %}